### PR TITLE
Update dtype slides.

### PR DESCRIPTION
**Pull request by rossbar**
Incorporate Sebastian's suggestions from #3

### CODE REVIEW

**Comment by rossbar** [comment]
@seberg Let me know if this looks okay.

The only thing I'm not entirely clear on is the "disentangle dtypes" statement. Is this a reference to things like `np.int0`?

**Comment by seberg** [comment]
Disentangle is maybe a silly word. What I meant is: Currently a lot of the logic is in functions in a way such as:

```
def can_cast(dtype1, dtyp2):
    if dtype1.kind == "i":
         ...
    elif dtype1.kind == "f":
         ...
    elif ...:
```
meaning that a lot of dtype specific logic is not logically split up into dtypes, but rather housed in functions that must be aware of all existing dtypes. (Additionally, there are a few places that duplicate nearly (but not always quite) identical logic.)

EDIT: Just to be clear, I think that example is on point, I did not actually check the current can cast code right now to make sure ;).

**Comment by seberg** [comment]
In any case, looks good to me.

**Comment by rossbar** [comment]
Got it, thanks for the clarification!

**Pull request merged**
